name             "farcryless"
maintainer       "Sean Coyne"
maintainer_email "sean@n42designs.com"
license          "Apache 2.0"
description      "Sets up the FarCry LESS Plugin Test Environment"
long_description "Sets up the FarCry LESS Plugin Test Environment"
version          "1.1.0"
supports         "linux"
depends          "mysql"
depends          "timezone_lwrp"
depends          "apache2"
depends          "git"
depends          "database"
depends          "mysql2_chef_gem"